name: news_cloud
description: A news application is a big interactive database that tells a news story.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/splash.png"

flutter_native_splash:
  image: assets/splash.png
  image_dark: assets/splash.png
  color_dark: "#000000"
  color: "#ffffff"

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter
  rename_app: ^1.3.2

flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
